### ISSUE TITLE
Custom fog crashes with the mods I have installed

### ISSUE THREAD

**Issue by Adamillo** [Setadokalo/custom-fog#33] opened 2022-03-28 05:48 UTC
I'll upload a log file
[crash-2022-03-28_07.46.13-client.txt](https://github.com/Setadokalo/custom-fog/files/8359956/crash-2022-03-28_07.46.13-client.txt)

**Comment by JosefLitos** [comment] 2022-03-29 19:31
this is a dupe of #32

**Closed** 2022-06-23 02:25 UTC
