### ISSUE TITLE
Game crashes at start - 1.18.2 - java.lang.RuntimeException: Mixin transformation of net.minecraft.class_758 failed

### ISSUE THREAD

**Issue by olalderh** [Setadokalo/custom-fog#34] opened 2022-03-31 02:25 UTC
Game crashes at start when using alone with fabric API (without other mods) in minecraft 1.18.2. I upload a log file.

[crash-2022-03-30_20.18.13-client.txt](https://github.com/Setadokalo/custom-fog/files/8385407/crash-2022-03-30_20.18.13-client.txt)

Currently using Fabric 0.48.0. I have tested with previous versions and it doesn't work either.

**Comment by JosefLitos** [comment] 2022-04-01 13:13
this is a dupe of #32

**Closed** 2022-06-23 02:25 UTC
